//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iznajmljivanje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Iznajmljivanje()
        {
            this.Osiguranjes = new HashSet<Osiguranje>();
        }
    
        public int id_iznajmljivanje { get; set; }
        public int id_kupac { get; set; }
        public int id_automobil { get; set; }
        public System.DateTime pocetni_datum { get; set; }
        public System.DateTime zavrsni_datum { get; set; }
        public int id_lokacija { get; set; }
        public string lokacija_preuzimanja { get; set; }
        public string lokacija_vracanja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Osiguranje> Osiguranjes { get; set; }
    }
}
