//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oprema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oprema()
        {
            this.OpremaAutomobilas = new HashSet<OpremaAutomobila>();
        }
    
        public int id_oprema { get; set; }
        public string ime_opreme { get; set; }
        public Nullable<int> id_tip_opreme { get; set; }
    
        public virtual TipOpreme TipOpreme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpremaAutomobila> OpremaAutomobilas { get; set; }
    }
}
