//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class OsiguranjeIznajmljivanja
    {
        public int id { get; set; }
        public Nullable<int> id_iznajmljivanje { get; set; }
        public Nullable<int> id_osiguranje { get; set; }
    
        public virtual Iznajmljivanje Iznajmljivanje { get; set; }
        public virtual Osiguranje Osiguranje { get; set; }
    }
}
