//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        public int id_rezervacija { get; set; }
        public int id_kupac { get; set; }
        public int id_automobil { get; set; }
        public int lokacija_preuzimanja { get; set; }
        public int lokacija_vracanja { get; set; }
    
        public virtual Automobil Automobil { get; set; }
        public virtual Kupac Kupac { get; set; }
        public virtual Lokacija Lokacija { get; set; }
        public virtual Lokacija Lokacija1 { get; set; }
    }
}
