//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class RezervacijaOpreme
    {
        public int id_rezervacija { get; set; }
        public int id_kategorija_opreme { get; set; }
    
        public virtual TipOpreme TipOpreme { get; set; }
        public virtual TipOpreme TipOpreme1 { get; set; }
    }
}
