//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpremaAutomobila
    {
        public int id_oprema_automobila { get; set; }
        public int id_oprema { get; set; }
        public int id_automobil { get; set; }
        public System.DateTime pocetni_datum { get; set; }
        public System.DateTime zavrsni_datum { get; set; }
    
        public virtual Automobil Automobil { get; set; }
        public virtual Oprema Oprema { get; set; }
    }
}
