//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class RezervacijaOpreme
    {
        public int id { get; set; }
        public Nullable<int> id_rezervacija { get; set; }
        public Nullable<int> id_oprema { get; set; }
    
        public virtual Oprema Oprema { get; set; }
        public virtual Rezervacija Rezervacija { get; set; }
    }
}
