//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upiti
    {
        public int id_upit { get; set; }
        public string predmet { get; set; }
        public string email { get; set; }
        public string opis { get; set; }
        public Nullable<int> idPoduzeca { get; set; }
    }
}
