//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZaposlenikUloge
    {
        public int id { get; set; }
        public Nullable<int> id_zaposlenik { get; set; }
        public Nullable<int> id_tip_zaposlenika { get; set; }
    
        public virtual TipZaposlenika TipZaposlenika { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
    }
}
